# Generated by Django 4.2 on 2023-07-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exp_date', models.DateField()),
                ('Exp_type', models.CharField(choices=[('RC', 'Recreational'), ('ELC', 'Electricity'), ('LM', 'Lift_maintain')], max_length=30)),
                ('Amt', models.IntegerField()),
            ],
        ),
    ]
