# Generated by Django 4.2 on 2023-07-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetModel',
            fields=[
                ('incomemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Income.incomemodel')),
            ],
            bases=('Income.incomemodel',),
        ),
    ]
