# Generated by Django 4.2 on 2023-07-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('flat_no', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Amount', models.IntegerField(default='Not paid')),
                ('maintenance_giver', models.CharField(max_length=30)),
            ],
        ),
    ]
